CREATE TABLE PACIENTE (
	Cedula INT NOT NULL,
	Nombre VARCHAR(15) NOT NULL,
	Apellido VARCHAR(15) NOT NULL,
	Edad INT NOT NULL,
	Nacionalidad  VARCHAR(20) NOT NULL,
	Internado VARCHAR(2) NOT NULL,
	UCI VARCHAR(2) NOT NULL,
	Region INT NOT NULL,
	Estado INT NOT NULL,
	PRIMARY KEY (Cedula)
);

CREATE TABLE ESTADO (
	Id INT NOT NULL IDENTITY(1,1),
	Descripcion VARCHAR(25),
	PRIMARY KEY (Id)
);

CREATE TABLE MEDICACION (
	Id INT NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL,
	CasaFarmaceutica VARCHAR(25) NOT NULL,
	Paciente INT NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE REGION(
	Id INT NOT NULL IDENTITY(1,1),
	Pais VARCHAR(30) NOT NULL,
	Estado VARCHAR(30) NOT NULL,
	PRIMARY KEY (Id)
);


CREATE TABLE MEDIDASANITARIA(
	Id INT NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL,
	Descripcion VARCHAR(60) NOT NULL,
	FechaInicio DATE NOT NULL,
	FechaFinal DATE NOT NULL,
	Region INT,
	PRIMARY KEY (Id)
);

CREATE TABLE HOSPITAL(
	Id INT NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL,
	Director VARCHAR(25) NOT NULL,
	Capacidad INT NOT NULL,
	Contacto VARCHAR(8) NOT NULL,
	CamasUCI INT NOT NULL,
	Region INT NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE CONTACTO(
	Cedula INT NOT NULL,
	Nombre VARCHAR(15) NOT NULL,
	Apellido VARCHAR(15) NOT NULL,
	Edad INT NOT NULL,
	Nacionalidad  VARCHAR(20) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	Region INT NOT NULL,
	Paciente INT,
	PRIMARY KEY (Cedula),

);

CREATE TABLE PATOLOGIA(
	Id INT NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(40) NOT NULL,
	Descripcion VARCHAR(60) NOT NULL,
	Sintomas VARCHAR(70) NOT NULL,
	Tratamiento VARCHAR(70) NOT NULL,
	Paciente INT NOT NULL ,
	PRIMARY KEY (Id)
);